version: '3.8'

services:
  dnd-fo:
    build:
      context: /var/dnd/FO
      dockerfile: Dockerfile
    image: dnd-fo
    container_name: dnd-fo
    ports:
      - "443:443"
    restart: always
    volumes:
      - /etc/ssl/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - /etc/ssl/private/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
      - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem

  dnd-express:
    build:
      context: /var/dnd/BO
      dockerfile: Dockerfile
    image: dnd-express
    container_name: dnd-express
    ports:
      - "3001:3001" 
    restart: always

  db:
    image: mysql:latest
    container_name: dnd-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - /var/dnd/mysql/data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: dnd-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: "3306"
#      PMA_USER: ${PMA_USER}
#      PMA_PASSWORD: ${PMA_PASSWORD}
    depends_on:
      - db
    ports:
      - "8081:80"
    restart: always

volumes:
  mysql-data:

