version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: "3306"
#      PMA_USER: ${PMA_USER}
#      PMA_PASSWORD: ${PMA_PASSWORD}
    depends_on:
      - db
    ports:
      - "8080:80"
    restart: always

volumes:
  mysql-data:
